### PR TITLE
Use Github Actions for building Wheels and not Travis

### LINKED ISSUE #19: Provide Windows Wheels
ebassi suggested it and has some example code here: https://github.com/anholt/libepoxy/blob/master/.appveyor.yml

### PR DESCRIPTION
**Pull request by naveen521kk**
This PR is:
- continuation of #191 
- Fixes #19 
- Builds and test windows wheels using Github Actions 
- Revert `.travis.yml` to how it was originally.
- Uploads as Artifact after each build

TODO:
- Correct it to upload to releases. 

cc
@stuaxo

### CODE REVIEW

**Comment by stuaxo** [comment]
I'll test the WHLs this evening (BST), with a view to giving a +1 to releasing them.

**Comment by naveen521kk** [comment]
Atleast we can this as whole without follow up PR @stuaxo

**Comment by naveen521kk** [comment]
The logic for uploading release is weird for me. What would you like to do? Like tell me the workflow how you want it to be?

**Comment by stuaxo** [comment]
>  Also, is the release ready? @stuaxo

Yeah, I think we can release the WHLs generated here, are good
https://github.com/naveen521kk/pycairo/actions/runs/234172269

I tested one on a fresh python install (that had never compiled pycairo), to be sure + all the tests pass.

> The logic for uploading release is weird for me. What would you like to do? Like tell me the workflow how you want it to be? @stuaxo and @lazka

These are good questions, I don't have answers without having some time to think + learn a bit more about workflows, maybe @lazka has some ideas.

If we move to actions, we should aim not to add too much complexity, adhering to DRY if possible.

This github actions example from cibuildwheel is pretty minimal + in a declarative style.
https://www.fromkk.com/posts/using-cibuildwheel-to-create-python-wheels/

**Comment by naveen521kk** [comment]
@lazka so can you or @lazka can release the wheels in PyPi?

**Comment by lazka** [comment]
GHA is much better, thanks!

**Comment by naveen521kk** [comment]
@lazka Can you upload the wheels to PyPI?

**Comment by lazka** [comment]
@naveen521kk I'll do it for the next release. ok?

**Comment by naveen521kk** [comment]
I think it would be good if you do for this release itself( Many are in need of it) . Just upload it and PyPi handles it. But yes you would need to run actions by changing the version in setup.py to 19.1. 
If you could tell many when next release it would be good if you couldn't upload for this one.

**Pull request merged**
