### PR TITLE
Update main pycairo GTK examples to GTK4

### PR DESCRIPTION
**Pull request by danyeaw**
This PR updates the 3 main GTK examples from GTK3 to GTK4 with Adwaita.

### CODE REVIEW

**Comment by lazka** [comment]
Just curious: what's the advantage of libadwaita here?

**Comment by danyeaw** [comment]
Hi @lazka, thanks for the review! I agree that it doesn't change the result much for this simple example, however, I was trying to be consistent with the GNOME tutorials. For example, the Window tutorial uses Adw here: https://developer.gnome.org/documentation/tutorials/beginners/components/window.html

I was thinking it would be better to keep the tutorials as consistent as possible for new users. If you prefer to have the pycairo examples without libadwaita, that's fine as well and I can update the PR. 👍

**Comment by lazka** [comment]
I see, thanks for the info. I was a bit afraid that not everyone has those deps installed.

Let's see if someone complains

**Comment by danyeaw** [comment]
Thanks @lazka!

**Pull request merged**
