### PR TITLE
setup.py: Support overriding pkg-config install directory

### PR DESCRIPTION
**Pull request by mgorny**
This includes two fixes:
1. Allowing override for `--pkgconfigdir=` to account for whenever the default doesn't work,
2. Improving the default to use `LIBDIR` config-var rather than `get_python_lib()` (explained in detail in commit message).

### CODE REVIEW

**Comment by mgorny** [comment]
Working on Azure build failure.

**Comment by mgorny** [comment]
@lazka, apparently LIBDIR is undefined on Windows. Could you suggest how to proceed? Should we be installing `.pc` files on Windows at all?

**Comment by lazka** [comment]
Yeah, we need .pc files on Windows too. Can you just add the pkgconfigdir option so we can look into LIBDIR later?

**Comment by mgorny** [comment]
@lazka, done.

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
