### PR TITLE
Get pkgconfig install dir from sysconfig

### PR DESCRIPTION
**Pull request by infirit**
This points to the dir where pythons pkconfig file is installed.

### CODE REVIEW

**Comment by lazka** [comment]
Th install command can also install into a random directory, like a virtualenv, or a temp director while packaging, so an absolute path wont work here. Not sure what the right thing to do is..

**Comment by lazka** [comment]
distutils.sysconfig.get_python_lib looks promising

**Comment by infirit** [comment]
>Not sure what the right thing to do is

Use autotools 😉 

Force pushed a new version of this commit. This hopefully handles most cases, it does on gentoo here.

**Comment by lazka** [comment]
I'd prefer 

```python
libdir = os.path.dirname(sysconfig.get_python_lib(True, True, self.install_data))
```

if that's OK with you. That function is at least documented.

**Comment by infirit** [comment]
>if that's OK with you

Sure, updated.

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
