### PR TITLE
Replace % formatting with fstrings.

### PR DESCRIPTION
**Pull request by stuaxo**
Use fstrings instead of % formatting, except for logging and in the C API.

### CODE REVIEW

**Comment by stuaxo** [comment]
Doh, didn't realise this is a python3.6 thing.

So probably not worth doing until 3.5 is dropped.

**Comment by lazka** [comment]
Ubuntu 16.04 has 3.5 and I still want to support that, so sadly, no :)

**Comment by stuaxo** [comment]
Fair enough. it looks like after 16.04, then next LTS is 18.04 which has python 3.6.

So maybe try again in 2021 when 16.04 LTS stops being supported ?

**Comment by lazka** [comment]
> So maybe try again in 2021 when 16.04 LTS stops being supported ?

definitely. at the latest.

**Comment by stuaxo** [comment]
I'll probably remember in about 2025 and re-open this PR then ! :D

**Pull request closed without merging**
