### PR TITLE
Added lots of examples

### PR DESCRIPTION
**Pull request by kolibril13**
An overview with lots of small snippets, collected in an jupyter notebook, so that the output can be seen just along with the code.
The examples include all examples from
https://github.com/pygobject/pycairo/tree/master/examples/cairo_snippets/snippets
and in addition one comes from
https://github.com/stuaxo/cairo-jupyter

### CODE REVIEW

**Comment by kolibril13** [comment]
Sorry, I still have to improve some things.

**Comment by kolibril13** [comment]
Ok, now the examples are cleaned up and understandable

**Comment by stuaxo** [comment]
I would look at jupytext if you are trying to add notebooks to a repo, it lets you store the notebooks in plain python or markdown (then generate ipynb as needed).

Though I'd see what @lazka thinks about having notebooks.

Personally I find then the easiest way to prototype this sort of stuff.
I should get some time to play with the notebooks themselves on the weekend.

**Comment by lazka** [comment]
I don't have much experience with jupyter, so if this seems in any way useful, go ahead.

An alternative to consider would be to link to an external example in the docs, but I don't mind it in the repo.

**Pull request merged**
